### PR TITLE
NET 8.0 compatibility

### PR DESCRIPTION
**Pull request by YvesPa**
I needed on a NET 8.0 project so I made it compatible.

I needed to remove IFileSystem and use Path and File directly. I have tested it on NET 6 and 8 but not on netstandard2.0

### CODE REVIEW

**Comment by YvesPa** [comment]
Btw on the CI after my previus pull request : 

> Publishing Synology.Api.Client.0.2.64.nupkg to https://www.nuget.org/api/v2/package...
> Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.

**Comment by YvesPa** [comment]
Look like it's needed for unitTest with MockupSystem. I will change it

**Comment by plneto** [comment]
> Btw on the CI after my previus pull request :
> 
> > Publishing Synology.Api.Client.0.2.64.nupkg to https://www.nuget.org/api/v2/package...
> > Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.

I've regenerated the API key.



> I needed on a NET 8.0 project so I made it compatible.
> 
> I needed to remove IFileSystem and use Path and File directly. I have tested it on NET 6 and 8 but not on netstandard2.0

It looks like the `System.IO.Abstractions` library is compatible with .NET 8. Is there a way to keep using it?

**Comment by YvesPa** [comment]
Yes at first I thought that it was useless because I work on my other project without the Tests projects. But yes I did a new commit and add Abstractions for NET8.0

**Pull request merged**
